app/routes/rutes.py
from flask import Blueprint, render_template

app_router = Blueprint('app_router', __name__)

@app_router.route('/')
def index():
    return render_template('index/index.html')


@app_router.route('/algoritmos')
def algoritm_simples():
    lista_1 = [
        {
            'id': 1,
            'titulo': 'Ejercicio 1',
            'description': ['Algoritmo que permita el ingreso de dos números enteros y calcule la división de ambos números.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/01-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/1.dfd'
        },
        {
            'id': 2,
            'titulo': 'Ejercicio 2',
            'description': ['Algoritmo que convierta soles a dólares.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/02-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/2.dfd'
        },
        {
            'id': 3,
            'titulo': 'Ejercicio 3',
            'description': ['Algoritmo que convierta kilómetros en metros y en centímetros.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/03-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/3.dfd'
        },
        {
            'id': 4,
            'titulo': 'Ejercicio 4',
            'description': ['Algoritmo que convierta horas en minutos y en segundos.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/04-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/4.dfd'
        },
        {
            'id': 5,
            'titulo': 'Ejercicio 5',
            'description': ['Algoritmo que convierta grados Celsius a grados Fahrenheit.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/05-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/5.dfd'
        },
        {
            'id': 6,
            'titulo': 'Ejercicio 6',
            'description': ['Algoritmo que eleve al cubo un número entero.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/06-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/6.dfd'
        },
        {
            'id': 7,
            'titulo': 'Ejercicio 7',
            'description': ['Algoritmo que calcule la distancia (MRU) sabiendo la velocidad y el tiempo recorrido por un móvil.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/07-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/7.dfd'
        },
        {
            'id': 8,
            'titulo': 'Ejercicio 8',
            'description': ['Algoritmo que calcule el salario mensual, sabiendo el número de horas trabajadas y el valor por hora.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/08-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/8.dfd'
        },
        {
            'id': 9,
            'titulo': 'Ejercicio 9',
            'description': ['Un docente desea saber el porcentaje de varones y mujeres que hay en un salón de clases; realice el algoritmo respectivo.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/09-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/9.dfd'
        },
        {
            'id': 10,
            'titulo': 'Ejercicio 10',
            'description': ['Un alumno desea saber el promedio de sus calificaciones teniendo en cuenta que:', '- El promedio de sus 4 tareas académicas es el 60% del promedio final.', '- El examen de medio curso es el 15% del promedio final.', '- El examen final es el 25% del promedio final.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/10-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/10.dfd'
        },
        {
            'id': 11,
            'titulo': 'Ejercicio 11',
            'description': ['Algoritmo que calcule el nuevo salario de un obrero, si obtuvo un incremento del 25% sobre su salario anterior.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/11-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/11.dfd'
        },
    ]
    return render_template('algoritmos/a-simples.html', lista_1=lista_1)


@app_router.route('/condicionales')
def algoritm_condicion():
    lista_1 = [
            {
                'id': 1,
                'titulo': 'Ejercicio 1',
                'description': ['Dado un número entero, determinar si es positivo, negativo o cero.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/01-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/1.dfd'
            },
            {
                'id': 2,
                'titulo': 'Ejercicio 2',
                'description': ['Dado un número natural, determinar si es cero, par o impar.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/02-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/2.dfd'
            },
            {
                'id': 3,
                'titulo': 'Ejercicio 3',
                'description': ['Dado las 4 notas de tareas académicas, el emc y el de fin de curso, calcule su promedio e imprima el mensaje respectivo o si ingresa al sustitutorio. En caso afirmativo, reemplazar la menor nota (emc o efc) con el sustitutorio y hallar el nuevo promedio final.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/03-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/3.dfd'
            },
            {
                'id': 4,
                'titulo': 'Ejercicio 4',
                'description': ['Determinar si un número entero es divisible entre otro.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/04-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/4.dfd'
            },
            {
                'id': 5,
                'titulo': 'Ejercicio 5',
                'description': ['Leer dos valores numéricos e imprimir en orden ascendente.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/05-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/5.dfd'
            },
            {
                'id': 6,
                'titulo': 'Ejercicio 6',
                'description': ['Leer la edad de una persona y escriba el mensaje respectivo si es mayor o menor de edad.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/06-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/6.dfd'
            },
            {
                'id': 7,
                'titulo': 'Ejercicio 7',
                'description': ['Hacer un programa que reciba datos de una persona y le dé una categoría según el siguiente criterio:', 'a) Adulto profesionista, si tiene un título y trabajo y tiene entre 20 y 50 años.', 'b) Adulto desempleado, si no tiene trabajo y tiene entre 20 y 50 años.', 'c) Joven estudiante, si estudia y tiene entre 15 y 20 años.', 'd) Joven desempleado, si no estudia y tiene entre 15 y 20 años.', 'e) Joven empleado, si no tiene título y trabaja, entre 15 y 20 años de edad.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/07-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/7.dfd'
            },
            {
                'id': 8,
                'titulo': 'Ejercicio 8',
                'description': ['Construir un programa que calcule el índice de masa corporal de una persona (IMC = peso [kg] /altura2 [m]) e indique el estado en el que se encuentra esa persona en función del valor de IMC:', 'Valor de IM< 16 Criterio de ingreso al hospital', 'de 16 a 17 infrapeso', 'de 17 a 18 bajo peso', 'de 18 a 25 peso normal (saludable)', 'de 25 a 30 sobrepeso (obesidad de grado I)', 'de 30 a 35 sobrepeso crónico (obesidad de grado II)', 'de 35 a 40 obesidad premórbida (obesidad de grado III)', '>40 obesidad mórbida (obesidad de grado IV)', 'Nota 1: se recomienda el empleo de sentencias if - else anidadas.', 'Nota 2: Los operandos (peso y altura) deben ser introducidos por teclado por el usuario.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/08-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/8.dfd'
            },
            {
                'id': 9,
                'titulo': 'Ejercicio 9',
                'description': ['Se reciben tres enteros positivos en forma ascendente a<=b<=c. Estos, pueden representar las longitudes de los lados de un triángulo si cumplen con (a + b)>c.', 'Si realmente representan un triángulo, encuentre su área e indique si es equilátero, isósceles o escaleno.', 'El área del triángulo se calcula mediante la siguiente fórmula:', 'Área =   √ s*(s-a) *(s-b) *(s-c)', 'Donde: s es la mitad de la suma de los lados a, b y c.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/09-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/9.dfd'
            },
            {
                'id': 10,
                'titulo': 'Ejercicio 10',
                'description': ['Dado un valor de “x” calcular el valor de “y” según la siguiente función:', '3x + 36 sí x <= 11', '2x - 10 sí 11 < x <= 33', 'x + 6 sí 33 < x <= 64', 'Y 0 para los demás valores de x'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/10-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/10.dfd'
            },
    ]

    return render_template('algoritmos/a-condicionales.html', lista_1=lista_1)


@app_router.route('/bucles-mq')
def bucle_mq():
    lista_1 = [
            {

app/templates/index/index.html
{% extends 'base.html' %}

{% block title %} {{ super() }} Inicio {% endblock %}

{% block teorhy %}    


    <!-- Seccion Hero -->

    <section class="align-items-stretch hero text-center">
      <div class="hero-principal d-flex flex-column justify-content-center
                  align-items-center">
        <img class="hero-img-cuaderno" src="{{ url_for('static', filename='img/generic/book.svg')}}" alt="foto generica">
        <h1>Cuaderno de Algoritmica - UDH</h1>
        <h2>Cuaderno virtual desarrollado en base a las clases hechas por el Ing. Ethel Jhovani Manzano Lozano</h2>
      </div>
      <div class="hero-inferior">
        <img class="hero-inferior-img img-fluid rounded-top" src="{{ url_for('static', filename='img/generic/banner.png')}}">
      </div>
    </section>

    <!-- Sobre el cuaderno -->
    <section class="sobre seccion-oscura">
      <div class="contenedor">
        <h2 class="seccion-titulo">Cuaderno Virtual de Algoritmica</h2>
        <p class="seccion-texto">Pagina web desarrollada con el propósito de impartir, todos los conocimientos brindados por el ingeniero Ethel Jhovani Manzano Lozano, hacia nosotros como estudiantes de la facultad de ingenieria de sistemas e informática de la Universidad de Huánuco (UDH), donde adjuntamos información en los temas de DFD y C++.</p>
      </div>
    </section>
  

    <!-- Seccion clases 1era parte -->


    <section class="proyectos-recientes seccion-clara d-flex flex-column text-center">
      <h2 class="seccion-titulo texto-negro">Primera Parte: Pseudocodigo y DFD</h2>
      <h3 class="seccion-descripcion">Esta sección te brindará conceptos básicos sobre lo que es un algoritmo, un pseudocódigo, un diagrama de flujo de datos o DFD y resolveremos algunos ejercicios.</h3>
    </section>

    <section class="clases seccion-clara">
      <div class="container text-center">
        <div class="row">
          <!--Ejercicios Simples-->
          <div class="columna col-12 col-md-6">
            <i class="bi bi-diagram-3"></i>
            <p class="clase-titulo">Algoritmos</p>
            <p>En esta sección, te daremos una introducción a <strong>algoritmos, pseudocódigos, diagramas y conceptos de lo que es un programa</strong>. También resolveremos algunos ejercicios.</p>
            <a class="btn btn-dark" href="{{ url_for('app_router.algoritm_simples')}}" role="button">Ver más</a>
          </div>
            
          <!--Ejercicios Condicionales-->
          <div class="columna col-12 col-md-6">
            <i class="bi bi-diagram-3"></i>
            <p class="clase-titulo">Condicionales</p>
            <p>En esta sección, aprenderemos el concepto de <strong>condicionales</strong> en algoritmos y resolveremos algunos ejercicios.</p>
            <a class="btn btn-dark" href="{{ url_for('app_router.algoritm_condicion')}}" role="button">Ver más</a>
          </div>
        </div>
        <div class="row">
          <div class="columna col-12 col-md-6">
            <i class="bi bi-diagram-3"></i>
            <p class="clase-titulo">Blucles MQ</p>
            <p>En esta sección, aprenderemos el concepto de bucles, nos enfocaremos en el <strong>bucle mientras que</strong>  y resolveremos algunos ejercicios.</p>
            <a class="btn btn-dark" href="{{ url_for('app_router.bucle_mq')}}" role="button">Ver más</a>
          </div>
          <div class="columna col-12 col-md-6">
            <i class="bi bi-diagram-3"></i>
            <p class="clase-titulo">Bucles FOR</p>
            <p>En esta sección, aprenderemos el concepto de bucles, nos enfocaremos en el <strong>bucle for o para</strong> y resolveremos algunos ejercicios.</p>
            <a class="btn btn-dark" href="{{ url_for('app_router.bucle_for')}}" role="button">Ver más</a>
          </div>
          <div class="columna col-12">
            <i class="bi bi-diagram-3"></i>
            <p class="clase-titulo">Arreglos</p>
            <p>Y finalmente, aprenderemos el concepto de <strong>arreglos</strong> o también conocido con el nombre de <strong>vectores</strong> y resolveremos algunos ejercicios.</p>
            <a class="btn btn-dark" href="{{ url_for('app_router.arrays')}}" role="button">Ver más</a>
          </div>
        </div>
      </div>
    </section>


    <!-- Seccion clases 2da parte -->

    <section class="proyectos-recientes seccion-clara d-flex flex-column text-center">
      <h2 class="seccion-titulo texto-negro">Segunda Parte: C++</h2>
      <h3 class="seccion-descripcion">En esta sección aprenderemos lo que es un lenguaje de pogramacion, realizaremos ejercicios en base a los ejercicios de la primera parte.</h3>
    </section>

    <section class="clases seccion-clara">
      <div class="container text-center">
        <div class="row">
          <div class="columna col-12 col-sm-6">
            <i class="bi bi-laptop"></i>
            <p class="clase-titulo">Algoritmos en C++</p>
            <p>Concepto de lo que es un lenguaje de pogramación y resolución de los mismos ejercicios de la sección <a href="{{url_for('app_router.algoritm_simples')}}" target="_blank"
              rel="noopener noreferrer">Algoritmos</a> en c++.</p>
            <a class="btn btn-dark" href="{{url_for('c_router.c_simples')}}" role="button">Ver más</a>
          </div>
          <div class="columna col-12 col-sm-6">
            <i class="bi bi-laptop"></i>
            <p class="clase-titulo">Condicionales en C++</p>
            <p>Resolución de los mismos ejercicios de la sección <a href="{{url_for('app_router.algoritm_condicion')}}" target="_blank"
              rel="noopener noreferrer">Condicionales</a> en c++.</p>
            <a class="btn btn-dark" href="{{url_for('c_router.c_condicional')}}" role="button">Ver más</a>
          </div>
        </div>
        <div class="row">
          <div class="columna col-12 col-sm-6">
            <i class="bi bi-laptop"></i>
            <p class="clase-titulo">Bucles While en C++</p>
            <p>La resolución de los mismos ejercicios de la sección  <a href="{{ url_for('app_router.bucle_mq')}}" target="_blank"
              rel="noopener noreferrer">Bucles MQ</a> pero en c++</p>
            <a class="btn btn-dark" href="{{url_for('c_router.c_bucle_mq')}}" role="button">Ver más</a>
          </div>
          <div class="columna col-12 col-sm-6">
            <i class="bi bi-laptop"></i>
            <p class="clase-titulo">Bucles FOR en C++</p>
            <p>La resolución de los mismos ejercicios de la sección 
               <a href="{{ url_for('app_router.bucle_for')}}" target="_blank"
              rel="noopener noreferrer">Bucles FOR</a>
               pero en c++</p>
            <a class="btn btn-dark" href="{{url_for('c_router.c_bucle_for')}}" role="button">Ver más</a>
          </div>
        </div>
        <div class="row">
          <div class="columna col">
            <i class="bi bi-laptop"></i>
            <p class="clase-titulo">Arreglos en C++</p>
            <p>La resolución de los mismos ejercicios de la sección 
              <a href="{{ url_for('app_router.arrays')}}" target="_blank"
              rel="noopener noreferrer">Arreglos</a>
              pero en c++</p>
            <a class="btn btn-dark" href="{{url_for('c_router.c_arreglos')}}" role="button">Ver más</a>
          </div>
        </div>
      </div>
    </section>
 
        



{% endblock %}