app/routes/rutes.py
from flask import Blueprint, render_template

app_router = Blueprint('app_router', __name__)

@app_router.route('/')
def index():
    return render_template('index/index.html')


@app_router.route('/algoritmos')
def algoritm_simples():
    lista_1 = [
        {
            'id': 1,
            'titulo': 'Ejercicio 1',
            'description': ['Algoritmo que permita el ingreso de dos números enteros y calcule la división de ambos números.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/01-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/1.dfd'
        },
        {
            'id': 2,
            'titulo': 'Ejercicio 2',
            'description': ['Algoritmo que convierta soles a dólares.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/02-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/2.dfd'
        },
        {
            'id': 3,
            'titulo': 'Ejercicio 3',
            'description': ['Algoritmo que convierta kilómetros en metros y en centímetros.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/03-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/3.dfd'
        },
        {
            'id': 4,
            'titulo': 'Ejercicio 4',
            'description': ['Algoritmo que convierta horas en minutos y en segundos.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/04-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/4.dfd'
        },
        {
            'id': 5,
            'titulo': 'Ejercicio 5',
            'description': ['Algoritmo que convierta grados Celsius a grados Fahrenheit.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/05-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/5.dfd'
        },
        {
            'id': 6,
            'titulo': 'Ejercicio 6',
            'description': ['Algoritmo que eleve al cubo un número entero.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/06-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/6.dfd'
        },
        {
            'id': 7,
            'titulo': 'Ejercicio 7',
            'description': ['Algoritmo que calcule la distancia (MRU) sabiendo la velocidad y el tiempo recorrido por un móvil.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/07-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/7.dfd'
        },
        {
            'id': 8,
            'titulo': 'Ejercicio 8',
            'description': ['Algoritmo que calcule el salario mensual, sabiendo el número de horas trabajadas y el valor por hora.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/08-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/8.dfd'
        },
        {
            'id': 9,
            'titulo': 'Ejercicio 9',
            'description': ['Un docente desea saber el porcentaje de varones y mujeres que hay en un salón de clases; realice el algoritmo respectivo.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/09-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/9.dfd'
        },
        {
            'id': 10,
            'titulo': 'Ejercicio 10',
            'description': ['Un alumno desea saber el promedio de sus calificaciones teniendo en cuenta que:', '- El promedio de sus 4 tareas académicas es el 60% del promedio final.', '- El examen de medio curso es el 15% del promedio final.', '- El examen final es el 25% del promedio final.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/10-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/10.dfd'
        },
        {
            'id': 11,
            'titulo': 'Ejercicio 11',
            'description': ['Algoritmo que calcule el nuevo salario de un obrero, si obtuvo un incremento del 25% sobre su salario anterior.'],
            'img_analisis': 'img/assets/assets/01-E-SimplesDFD/11-Análisis.png',
            'dfd': 'img/assets/archives/Ficha 1/Ejercicios-Ficha-1-DFD/11.dfd'
        },
    ]
    return render_template('algoritmos/a-simples.html', lista_1=lista_1)


@app_router.route('/condicionales')
def algoritm_condicion():
    lista_1 = [
            {
                'id': 1,
                'titulo': 'Ejercicio 1',
                'description': ['Dado un número entero, determinar si es positivo, negativo o cero.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/01-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/1.dfd'
            },
            {
                'id': 2,
                'titulo': 'Ejercicio 2',
                'description': ['Dado un número natural, determinar si es cero, par o impar.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/02-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/2.dfd'
            },
            {
                'id': 3,
                'titulo': 'Ejercicio 3',
                'description': ['Dado las 4 notas de tareas académicas, el emc y el de fin de curso, calcule su promedio e imprima el mensaje respectivo o si ingresa al sustitutorio. En caso afirmativo, reemplazar la menor nota (emc o efc) con el sustitutorio y hallar el nuevo promedio final.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/03-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/3.dfd'
            },
            {
                'id': 4,
                'titulo': 'Ejercicio 4',
                'description': ['Determinar si un número entero es divisible entre otro.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/04-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/4.dfd'
            },
            {
                'id': 5,
                'titulo': 'Ejercicio 5',
                'description': ['Leer dos valores numéricos e imprimir en orden ascendente.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/05-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/5.dfd'
            },
            {
                'id': 6,
                'titulo': 'Ejercicio 6',
                'description': ['Leer la edad de una persona y escriba el mensaje respectivo si es mayor o menor de edad.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/06-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/6.dfd'
            },
            {
                'id': 7,
                'titulo': 'Ejercicio 7',
                'description': ['Hacer un programa que reciba datos de una persona y le dé una categoría según el siguiente criterio:', 'a) Adulto profesionista, si tiene un título y trabajo y tiene entre 20 y 50 años.', 'b) Adulto desempleado, si no tiene trabajo y tiene entre 20 y 50 años.', 'c) Joven estudiante, si estudia y tiene entre 15 y 20 años.', 'd) Joven desempleado, si no estudia y tiene entre 15 y 20 años.', 'e) Joven empleado, si no tiene título y trabaja, entre 15 y 20 años de edad.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/07-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/7.dfd'
            },
            {
                'id': 8,
                'titulo': 'Ejercicio 8',
                'description': ['Construir un programa que calcule el índice de masa corporal de una persona (IMC = peso [kg] /altura2 [m]) e indique el estado en el que se encuentra esa persona en función del valor de IMC:', 'Valor de IM< 16 Criterio de ingreso al hospital', 'de 16 a 17 infrapeso', 'de 17 a 18 bajo peso', 'de 18 a 25 peso normal (saludable)', 'de 25 a 30 sobrepeso (obesidad de grado I)', 'de 30 a 35 sobrepeso crónico (obesidad de grado II)', 'de 35 a 40 obesidad premórbida (obesidad de grado III)', '>40 obesidad mórbida (obesidad de grado IV)', 'Nota 1: se recomienda el empleo de sentencias if - else anidadas.', 'Nota 2: Los operandos (peso y altura) deben ser introducidos por teclado por el usuario.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/08-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/8.dfd'
            },
            {
                'id': 9,
                'titulo': 'Ejercicio 9',
                'description': ['Se reciben tres enteros positivos en forma ascendente a<=b<=c. Estos, pueden representar las longitudes de los lados de un triángulo si cumplen con (a + b)>c.', 'Si realmente representan un triángulo, encuentre su área e indique si es equilátero, isósceles o escaleno.', 'El área del triángulo se calcula mediante la siguiente fórmula:', 'Área =   √ s*(s-a) *(s-b) *(s-c)', 'Donde: s es la mitad de la suma de los lados a, b y c.'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/09-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/9.dfd'
            },
            {
                'id': 10,
                'titulo': 'Ejercicio 10',
                'description': ['Dado un valor de “x” calcular el valor de “y” según la siguiente función:', '3x + 36 sí x <= 11', '2x - 10 sí 11 < x <= 33', 'x + 6 sí 33 < x <= 64', 'Y 0 para los demás valores de x'],
                'img_analisis': 'img/assets/assets/02-E-Condicionales/10-Análisis.png',
                'dfd': 'img/assets/archives/Ficha 2/Ejercicios-Ficha-2-DFD/10.dfd'
            },
    ]

    return render_template('algoritmos/a-condicionales.html', lista_1=lista_1)


@app_router.route('/bucles-mq')
def bucle_mq():
    lista_1 = [
            {

app/templates/includes/c-exercises.html
<div class="container">
    <!-- Ejercicios -->
{% for exercise in lista_2 %}
<div class="row d-flex justify-content-center align-items-center">
  <div class="columna col-12 col-md-8">
    <section class="columna seccion-clara">
      <br>
      <h2>{{exercise.titulo}}</h2>
      <br>
      <div style="justify-content: justify;">  
      {% for line in exercise.description %}
        <p style="font-size: 20;">{{line}}</p>
      {% endfor %}
      <p style="font-size: 14px;" class="text-danger">Para poder probar el ejercicio haga click en el boton de abajo <strong>Mostrar</strong> y click en el botón <strong>Run</strong>, en ese mismo lugar podra ver el código tan solo haga <strong>click en 'show files',</strong> y seleccione el archivo <strong>main.cpp.</strong> </p>
      </div>   
      <p>
        {% if exercise.link_replit %}
        <button class="btn btn-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample{{exercise.id}}" aria-expanded="false" aria-controls="collapseExample{{exercise.id}}">
          Mostrar
        </button>
        {% else %}
        <button class="btn btn-dark" disabled type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample{{exercise.id}}" aria-expanded="false" aria-controls="collapseExample{{exercise.id}}">
          Proximamente
        </button>
        {% endif %}
      </p>


    </section>
    <div class="collapse" id="collapseExample{{exercise.id}}">
      <div class="d-flex justify-content-center align-items-center">
        <iframe frameborder="0" width="100%" height="500px" src="{{exercise.link_replit}}"></iframe>
      </div>
    </div>
    <hr>
  </div>
</div>
    
{% endfor %}
    
</div>

app/templates/includes/exercises.html
<div class="container text-center">

  {% for exercise in lista_1 %}
  
    <!-- Ejercicios -->
    <section id="proyectos" class="proyectos-recientes seccion-clara d-flex flex-column">
      <h2>{{ exercise.titulo }}</h2>
      <!-- Galeria de Ejercicios -->
      <div class="container text-center proyectos-contenedor">
        <div class="row">
          <!-- Ejercicio -->
          <div class="col-12 col-md-4">
            <div class="proyecto">
              <img class="img_ejercicio" src="{{url_for('static', filename='img/generic/analisis.jpg')}}" alt="Proyecto 1">
              <div class="overlay">
                <p>Ejercicio</p>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#exerciseModal{{exercise.id}}">
                  Mostrar
                </button>
              </div>
              <!-- Modal -->
              <div class="modal fade" id="exerciseModal{{exercise.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">{{ exercise.titulo }}</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" style="text-align: justify;">
                      {% for line in exercise.description %}
                      <p>{{line}}</p>
                      {% endfor %}
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>       
          <!-- Analisis -->
          <div class="col-12 col-md-4">
            <div class="proyecto">
              <img class="img_ejercicio" src="{{url_for('static', filename='img/generic/analisis.jpg')}}" alt="Proyecto 1">
              <div class="overlay">
                <p>Análisis</p>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#analisisModal{{exercise.id}}">
                  Mostrar
                </button>
              </div>
              <!-- Modal -->
              <div class="modal fade" id="analisisModal{{exercise.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">Análisis</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <div class="modal-body-img">
                        {% if exercise.img_analisis_parte1 %}
                        <div class="d-flex flex-column">
                          <img class="img_analisis" src="{{url_for('static', filename=exercise.img_analisis_parte1)}}">                    
                          <img class="img_analisis" src="{{url_for('static', filename=exercise.img_analisis_parte2)}}">
                        </div>
                        {% else %}
                        <img class="img_analisis" src="{{url_for('static', filename=exercise.img_analisis)}}">
                        {% endif %}
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- DFD -->
          <div class="col-12 col-md-4">
            <div class="proyecto">
              <img class="img_ejercicio" src="{{url_for('static', filename='img/generic/analisis.jpg')}}" alt="Proyecto 1">
              <div class="overlay">
                <p>DFD</p>
                {% if exercise.dfd %}
                <a type="button" href="{{url_for('static', filename=exercise.dfd)}}" class="btn btn-dark" download>Descargar</a>    
                {% else %}
                <a href="#" class="btn btn-dark disabled" tabindex="-1" role="button" aria-disabled="true">Proximamente</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <hr>
  
  
  {% endfor %}
  
</div>

app/templates/includes/footer.html
<!-- Pie de pagina (footer) -->
<footer class="seccion-oscura d-flex flex-column align-items-center justify-content-center">
  <p class="footer-texto text-center">Código:</p>
  <div class="iconos-redes-sociales d-flex flex-wrap align-items-center justify-content-center">
    <a href="https://github.com/LilXhan/book-udh" target="_blank" rel="noopener noreferrer">
      <i class="bi bi-github"></i>
    </a>
  </div>
  <div class="derechos-de-autor text-center">Creado por Karol, Flavio, Yorbi, Josh y Angel (2022) &#169;</div>
</footer>

app/templates/includes/navbar.html
<!-- Barra de navegacion -->
<nav class="navbar navbar-expand-md navbar-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-toggler"
      aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between align-items-center" id="navbar-toggler">
      <a class="navbar-brand" href="http://www.udh.edu.pe/" target="_blank">
        <img src="{{ url_for('static', filename='img/generic/download.png')}}" width="50" height="50" alt="logo-pagina">
      </a>
      <ul class="navbar-nav d-flex justify-content-center align-items-center">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"
            href="{{ url_for('app_router.index')}}"><strong>Inicio</strong></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/includes/script.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>